import { Tool } from "./tool"
import z from "zod"

const DESCRIPTION = "Generate wordlists and perform brute-force enumeration"

const PARAMETERS = z.object({
  action: z.enum(["generate", "crack-hash"]).describe("Action to perform"),
  type: z.enum(["passwords", "usernames", "filenames", "subdomains"]).optional().describe("Wordlist type"),
  length: z.number().optional().describe("Password length for generation"),
  count: z.number().optional().describe("Number of combinations to generate"),
  charset: z.string().optional().describe("Character set (e.g., 'a-z', 'A-Z', '0-9')"),
})

export const WordlistTool = Tool.define("wordlist", async () => {
  return {
    description: DESCRIPTION,
    parameters: z.object({
      action: z.enum(["generate", "crack-hash"]).describe("Action to perform"),
      type: z.enum(["passwords", "usernames", "filenames", "subdomains"]).optional().describe("Wordlist type"),
      length: z.number().optional().describe("Password length for generation"),
      count: z.number().optional().describe("Number of combinations to generate"),
      charset: z.string().optional().describe("Character set (e.g., 'a-z', 'A-Z', '0-9')"),
    }),
    async execute(params) {
      const commonPasswords = [
        "123456",
        "password",
        "12345678",
        "qwerty",
        "123456789",
        "12345",
        "1234",
        "111111",
        "1234567",
        "dragon",
        "123123",
        "baseball",
        "abc123",
        "football",
        "monkey",
        "letmein",
        "696969",
        "shadow",
        "master",
        "666666",
        "qwertyuiop",
        "123321",
        "mustang",
        "1234567890",
        "michael",
        "654321",
        "pussy",
        "superman",
        "1qaz2wsx",
        "7777777",
        "fuckyou",
        "121212",
        "000000",
        "qazwsx",
        "123qwe",
        "killer",
        "trustno1",
        "jordan",
        "jennifer",
        "zxcvbnm",
        "asdfgh",
        "hunter",
        "buster",
        "soccer",
        "harley",
        "batman",
        "andrew",
        "tigger",
        "sunshine",
        "iloveyou",
        "fuckme",
        "2000",
        "charlie",
        "robert",
        "thomas",
        "hockey",
        "ranger",
        "daniel",
        "starwars",
        "klaster",
        "112233",
        "george",
        "computer",
        "michelle",
        "jessica",
        "pepper",
        "1111",
        "zxcvbn",
        "555555",
        "11111111",
        "131313",
        "freedom",
        "777777",
        "pass",
        "fuck",
        "maggie",
        "159753",
        "aaaaaa",
        "ginger",
        "princess",
        "joshua",
        "cheese",
        "amanda",
        "secret",
        "summer",
        "love",
        "ashley",
        "6969",
        "nicole",
        "chelsea",
        "biteme",
        "matthew",
        "access",
      ]

      const commonUsernames = [
        "admin",
        "root",
        "user",
        "guest",
        "test",
        "demo",
        "default",
        "backup",
        "administrator",
        "webadmin",
        "operator",
        "super",
        "master",
        "owner",
        "support",
        "helpdesk",
        "info",
        "information",
        "sales",
        "contact",
        "postmaster",
        "abuse",
        "noreply",
        "no-reply",
        "service",
        "services",
        "api",
        "developer",
        "dev",
        "test",
        "testing",
        "staging",
        "john",
        "jane",
        "mike",
        "sarah",
        "david",
        "jennifer",
        "michael",
        "chris",
        "tom",
        "admin1",
        "admin2",
        "user1",
        "test1",
        "ftp",
        "ssh",
        "telnet",
        "vpn",
        "oracle",
        "mysql",
        "postgres",
      ]

      const commonFilenames = [
        "index",
        "index.html",
        "index.php",
        "default",
        "default.html",
        "home",
        "home.html",
        "main",
        "main.html",
        "dashboard",
        "panel",
        "admin",
        "admin.html",
        "administrator",
        "login",
        "login.html",
        "wp-login",
        "wp-admin",
        "wp-content",
        "admin.php",
        "login.php",
        "config",
        "configuration",
        "settings",
        "config.php",
        "settings.php",
        "database",
        "db",
        "backup",
        "backups",
        "backup.sql",
        "dump.sql",
        "test",
        "test.html",
        "debug",
        "debug.log",
        "error.log",
        "logs",
        "api",
        "api.php",
        "rest",
        "graphql",
        "v1",
        "v2",
        "robots.txt",
        "sitemap.xml",
        ".htaccess",
        "web.config",
        "readme",
        "README.md",
        "CHANGELOG.md",
        "LICENSE",
        "package.json",
        "phpinfo",
        "info.php",
        "server-status",
        "server-info",
        ".git",
        ".git/config",
        ".git/HEAD",
        ".gitignore",
        ".env",
        ".env.local",
        "config.json",
        "settings.json",
      ]

      const commonSubdomains = [
        "www",
        "mail",
        "ftp",
        "admin",
        "blog",
        "dev",
        "test",
        "staging",
        "api",
        "cdn",
        "cdn1",
        "static",
        "assets",
        "images",
        "img",
        "shop",
        "store",
        "app",
        "mobile",
        "m",
        "support",
        "help",
        "docs",
        "documentation",
        "wiki",
        "forum",
        "community",
        "gitlab",
        "github",
        "jenkins",
        "ci",
        "build",
        "deploy",
        "vpn",
        "proxy",
        "gateway",
        "router",
        "firewall",
        "ns1",
        "ns2",
        "dns1",
        "dns2",
        "mx",
        "mx1",
        "smtp",
        "pop",
        "imap",
        "webmail",
        "owa",
        "crm",
        "erp",
        "hrm",
        "payroll",
        "accounting",
        "hr",
        "intranet",
        "extranet",
        "portal",
        "backup",
        "backups",
        "archive",
        "old",
        "legacy",
      ]

      let words: string[] = []

      if (params.action === "generate") {
        switch (params.type) {
          case "passwords":
            words = commonPasswords
            break
          case "usernames":
            words = commonUsernames
            break
          case "filenames":
            words = commonFilenames
            break
          case "subdomains":
            words = commonSubdomains
            break
          default:
            words = commonPasswords
        }
      }

      const maxCount = params.count || words.length
      const limited = words.slice(0, maxCount)

      let output = `## Wordlist Generator\n\n`
      output += `**Type**: ${params.type || "passwords"}\n`
      output += `**Total Words**: ${words.length}\n`
      output += `**Showing**: ${limited.length}\n\n`
      output += `\`\`\`\n${limited.join("\n")}\n\`\`\``

      return {
        title: "Wordlist Generator",
        output,
        metadata: { action: "wordlist", type: params.type || "passwords", count: limited.length, result: "success" },
      }
    },
  }
})
